/**
 * Golden tests: decode the user's original files with the TS decoders and compare SHA-256 against
 * test/golden/hashes.json (generated by tools/gen_golden.py from the Python decoders, which are verified
 * against the game's memory in DOSBox-X). No game bytes live in the repo: set MM_DATA_DIR (default ../MicroMac).
 */
import { describe, it, expect } from 'vitest';
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, relative } from 'node:path';
import { lzDecode } from '../../src/data/lzcodec';
import { decodePalette } from '../../src/data/palette';
import { decodeTileMap } from '../../src/data/tilemap';
import { decodeBlocks, expandMap } from '../../src/data/blocks';
import { decodeVehicle, frameTableBytes } from '../../src/data/sprites';
import { unpackPklite } from '../../src/data/pklite';

const DATA_DIR = process.env['MM_DATA_DIR'] ?? join(process.cwd(), 'MicroMac');
const hashes = JSON.parse(readFileSync(join(process.cwd(), 'test/golden/hashes.json'), 'utf8')) as
  Record<string, { sha256: string; length?: number; consumed?: number }>;

function listFiles(dir: string): string[] {
  const out: string[] = [];
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) out.push(...listFiles(p)); else out.push(p);
  }
  return out;
}
const files = existsSync(DATA_DIR) ? listFiles(DATA_DIR) : [];
const byName = new Map(files.map(p => [relative(DATA_DIR, p).toLowerCase().replace(/\\/g, '/'), p]));
const read = (name: string): Uint8Array => {
  const p = byName.get(name.toLowerCase());
  if (!p) throw new Error(`missing ${name}`);
  return new Uint8Array(readFileSync(p));
};
const sha = (b: Uint8Array): string => createHash('sha256').update(b).digest('hex');
const have = files.length > 0;

describe.skipIf(!have)('PKLITE depacker vs golden hash', () => {
  // everything else here decodes files the depacker produced, so this is the one that has to hold first
  it('pklite/MICRO.EXE.image', () => {
    const g = hashes['pklite/MICRO.EXE.image']!;
    const { image, relocs } = unpackPklite(read('MICRO.EXE'));
    expect(image.length).toBe(g.length);
    expect(relocs.length).toBe((g as { relocs?: number }).relocs);
    expect(sha(image)).toBe(g.sha256);
  });
});

describe.skipIf(!have)('LZ codec vs golden hashes', () => {
  const lzEntries = Object.entries(hashes).filter(([k]) => k.startsWith('lz/'));
  it('has golden entries', () => expect(lzEntries.length).toBeGreaterThan(0));
  for (const [key, g] of lzEntries) {
    const base = key.slice(3);
    it(key, () => {
      const name = [...byName.keys()].find(k => k.endsWith('/' + base.toLowerCase()) || k === base.toLowerCase());
      expect(name, `file ${base} present`).toBeTruthy();
      const r = lzDecode(read(name!));
      expect(r.length).toBe(g.length);
      expect(r.consumed).toBe(g.consumed);
      expect(sha(r.data)).toBe(g.sha256);
    });
  }
});

describe.skipIf(!have)('track data decoders', () => {
  it('palettes are 6-bit', () => {
    for (let r = 1; r <= 9; r++) expect(decodePalette(read(`GAME1/ROUND${r}.PAL`)).rgb6.length).toBe(768);
    expect(decodePalette(read('INTRO.PAL')).rgb6.length).toBe(768);
  });
  it('round 2 track 1 expands to a 192x192 world', () => {
    const blk = decodeBlocks(read('GAME1/ROUND2BR.CT'), read('GAME1/ROUND2.COL'), read('GAME1/ROUND2.DIR'), read('GAME1/ROUND2BR.LEV'));
    const map = decodeTileMap(read('GAME1/ROUND21.MAP'));
    const world = expandMap(blk, map.blocks);
    expect(world.length).toBe(192 * 192);
    expect(Math.max(...map.progress.filter(v => v !== 0xFF))).toBe(28);   // [2652] in the game's memory
  });
  it('vehicle table has 32 frames and frame 8 is frame 0 rotated 90 degrees (round 2)', () => {
    const v = decodeVehicle(lzDecode(read('GAME1/ROUND2BR.VH0')).data, 2);
    expect(v.frames.length).toBe(32);
    expect(frameTableBytes(v).length).toBe(0x4800);
    const w = 24;
    const overlap = (rot: (x: number, y: number) => number): number => {
      let same = 0, union = 0;
      for (let y = 0; y < w; y++) for (let x = 0; x < w; x++) {
        const a = v.frames[8]![y * w + x]! !== 0, b = v.frames[0]![rot(x, y)]! !== 0;
        if (a && b) same++; if (a || b) union++;
      }
      return same / union;
    };
    const best = Math.max(overlap((x, y) => x * w + (w - 1 - y)), overlap((x, y) => (w - 1 - x) * w + y));
    expect(best).toBeGreaterThan(0.9);
  });
});
